version: '3'

services:
  php:
    image: php:7.4-fpm
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./application:/var/www
    ports:
      - 9000:9000
    networks:
      - backend
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    volumes:
      - ./docker/nginx/local/nginx.conf:/etc/nginx/templates
      - ./application/public:/var/www/public
    networks:
      - backend
    links:
      - php
    depends_on:
      - php
  mysql:
    image: mysql:5.7
    ports:
      - 10001:3306
    environment:
      - MYSQL_ROOT_PASSWORD=456213456dsa456ADS456dsa45621345
      - MYSQL_DATABASE=app
      - MYSQL_USER=root
      - MYSQL_PASSWORD=LKhi9217hy3987hsdauty213
    volumes:
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./data/mysql:/var/lib/mysql
    networks:
      - backend
  redis:
    image: redis:latest
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - backend
  echo-server:
    image: oanhnn/laravel-echo-server
    volumes:
      - ./docker/laravel-echo-server/prod/laravel-echo-server.json:/app/laravel-echo-server.json
    ports:
      - "6001:6001"
    networks:
      - backend
  hub:
    image: selenium/hub:3.141.59-20200525
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59-20200525
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    deploy:
      replicas: 1
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
networks:
  backend:
    external: true
