version: '3'

services:
  php:
    image: bitnami/php-fpm:latest
    volumes:
      - ./docker/php/php.ini:/opt/bitnami/php/etc/php.ini
      - ./application:/app
    ports:
      - 9000:9000
    networks:
      - backend
  nginx:
    image: bitnami/nginx:latest
    ports:
      - 8081:80
      - 8443:8443
    volumes:
      - ./docker/nginx/local/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/myapp.conf
    #  - ./docker/nginx/log:/var/log/nginx
    #  - ./application:/app
    networks:
      - backend
    links:
      - php
    depends_on:
      - php
  mysql:
    image: bitnami/mysql:latest
    ports:
      - 10001:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123654897asd4213#@!6131268d4sa@!#"
      MYSQL_DATABASE: "app"
      MYSQL_USER: "guest"
      MYSQL_PASSWORD: "1q2w3e4r5t"
      MYSQL_AUTHENTICATION_PLUGIN: "mysql_native_password"
    volumes:
      #- ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./data/mysql:/bitnami/mysql/data
    networks:
      - backend
networks:
  backend:
    external: true
